# Generated by Django 2.2.2 on 2020-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nok1_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nok1_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nok1_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle')], max_length=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nok2_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
