# Generated by Django 2.2.2 on 2020-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200104_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='house_address',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lga',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prev_school',
            field=models.TextField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='resident_type',
            field=models.CharField(blank=True, choices=[('Day Student', 'Day Student'), ('Boarding Student', 'Boarding Student')], max_length=20),
        ),
    ]
