# Generated by Django 2.2.2 on 2020-01-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200104_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_class',
            field=models.CharField(blank=True, choices=[('JSS 1 BLUE', 'JSS 1 BLUE'), ('JSS 1 GREEN', 'JSS 1 GREEN'), ('JSS 1 YELLOW', 'JSS 1 YELLOW'), ('JSS 2 BLUE', 'JSS 2 BLUE'), ('JSS 2 GREEN', 'JSS 2 GREEN'), ('JSS 2 YELLOW', 'JSS 1 YELLOW'), ('JSS 3 BLUE', 'JSS 3 BLUE'), ('JSS 3 GREEN', 'JSS 3 GREEN'), ('JSS 3 YELLOW', 'JSS 1 YELLOW'), ('SSS 1 HARMONY', 'SSS 1 HARMONY'), ('SSS 1 SMART', 'SSS 1 SMART'), ('SSS 1 SPECIAL', 'SSS 1 SPECIAL'), ('SSS 2 HARMONY', 'SSS 2 HARMONY'), ('SSS 2 SMART', 'SSS 2 SMART'), ('SSS 2 SPECIAL', 'SSS 2 SPECIAL'), ('SSS 3 HARMONY', 'SSS 3 HARMONY'), ('SSS 3 SMART', 'SSS 3 SMART'), ('SSS 3 SPECIAL', 'SSS 3 SPECIAL')], max_length=10),
        ),
    ]
