# Generated by Django 2.2.2 on 2020-01-09 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200106_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('ca1_score', models.PositiveIntegerField(blank=True)),
                ('ca2_score', models.PositiveIntegerField(blank=True)),
                ('exam_score', models.PositiveIntegerField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=80)),
                ('remark', models.CharField(blank=True, max_length=80)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
