# Generated by Django 2.2.2 on 2020-02-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_subjectz'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport',
            field=models.ImageField(blank=True, default='static/default.jpg', upload_to='passports'),
        ),
    ]
