# Generated by Django 2.2.2 on 2020-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200202_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passport',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='passports'),
        ),
    ]
