# Generated by Django 2.2.2 on 2020-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200204_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('teacher', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
    ]
