# Generated by Django 2.2.2 on 2020-03-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200326_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectz',
            name='ca1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectz',
            name='ca2_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectz',
            name='exam_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
