# Generated by Django 2.2.2 on 2020-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20200329_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectz',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
