# Generated by Django 2.2.2 on 2020-04-03 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_subjectz_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectz',
            name='term',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='Subject_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('ca1_score', models.PositiveIntegerField(default=0)),
                ('ca2_score', models.PositiveIntegerField(default=0)),
                ('exam_score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=80)),
                ('remark', models.CharField(blank=True, max_length=80)),
                ('term', models.CharField(blank=True, max_length=80)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Subject_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('ca1_score', models.PositiveIntegerField(default=0)),
                ('ca2_score', models.PositiveIntegerField(default=0)),
                ('exam_score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=80)),
                ('remark', models.CharField(blank=True, max_length=80)),
                ('term', models.CharField(blank=True, max_length=80)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
