# Generated by Django 2.2.2 on 2020-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
