# Generated by Django 2.2.2 on 2020-05-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_payment_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='access_code',
        ),
    ]
